### ISSUE TITLE
Socket is closed for some reason

### ISSUE THREAD

**Issue by freezepro** [Coinigy/PureSocketCluster#5]
I've tried to run a socket client with many currencies for 1 day but it stopped to work sometime within 24hours, but no error appeared. Any indication why that happened? should I reconnect, I would like to have no issues if I use your product. 

Thus another issue happened after receiving about 2000 events(trade data) from socket server, 
Here's a log: 
------
{"event":"#disconnect","data":{"code":4005}}
Error: System.Net.WebSockets.WebSocketException (0x80004005): The 'System.Net.WebSockets.InternalClientWebSocket' instance cannot be used for communication because it has been transitioned into the 'Aborted' state. ---> System.Net.WebSockets.WebSocketException (0x80004005): The 'System.Net.WebSockets.InternalClientWebSocket' instance cannot be used for communication because it has been transitioned into the 'Aborted' state. ---> System.OperationCanceledException: The operation was canceled.
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at System.Net.WebSockets.WebSocketBase.ThrowIfConvertibleException(String methodName, Exception exception, CancellationToken cancellationToken, Boolean aborted)
   at System.Net.WebSockets.WebSocketBase.<CloseOutputAsyncCore>d__51.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.WebSockets.WebSocketBase.<CloseAsyncCore>d__56.MoveNext()
   at System.Net.WebSockets.WebSocketBase.ThrowIfAborted(Boolean aborted, Exception innerException)
   at System.Net.WebSockets.WebSocketBase.ThrowIfConvertibleException(String methodName, Exception exception, CancellationToken cancellationToken, Boolean aborted)
   at System.Net.WebSockets.WebSocketBase.<CloseAsyncCore>d__56.MoveNext()
   at System.Net.WebSockets.WebSocketBase.ThrowIfAborted(Boolean aborted, Exception innerException)
   at System.Net.WebSockets.WebSocketBase.ThrowIfConvertibleException(String methodName, Exception exception, CancellationToken cancellationToken, Boolean aborted)
   at System.Net.WebSockets.WebSocketBase.<CloseAsyncCore>d__56.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PureWebSockets.PureWebSocket.<<StartListener>b__80_0>d.MoveNext()
{"event":"#publish","data":{"channel":"TRADE-BTRX--LTC--BTC","data":{"market_history_id":135853053498,"exchange":"BTRX","marketid":0,"label":"LTC/BTC","tradeid":"90190991","time":"2017-11-02T22:35:12","price":0.007537,"quantity":13.27,"total":0.10001599,"timestamp":"2017-11-02T22:35:55Z","time_local":"2017-11-02 22:35:12","type":"BUY","exchId":0,"channel":"TRADE-BTRX--LTC--BTC"}}}
Opened

Opened
Socket Closed: 4005

Socket Closed: 4005
Socket Closed: 4005
Socket Closed: 4005
Socket Closed: 4005

**Comment by LadislavBohm** [comment]
Can someone from Coinigy actually respond to this? I now dont know wheter using this library/coinigy product is safe for production.
@freezepro Did you solve this issue somehow?

**Comment by ByronAP** [comment]
It is common for websocket connections to be occasionally dropped. You should always monitor the state of the connection and watch for error or fatal events. This is not a code issue.
